# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160616_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 16, 17, 47, 38, 67814, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
